### ISSUE TITLE
Client loses focus when Paint is clicked.

### ISSUE THREAD

**Issue by Fryslan** [Parabot/Parabot#110]
The Parabot client is losing focus when Paintable item is being clicked, this prevents us from using mouselisteners in paints.
Context.getInstance().getApplet()#addMouseEvents doest work eighter becouse the focus is lost from the applet aswell.

**Comment by JKetelaar** [comment]
Thanks, will look into it.

Any specific server(s)?

**Comment by JKetelaar** [comment]
What if you try this with disabling the dialog @Fryslan?

**Comment by Fryslan** [comment]
@JKetelaar then the paint wont show right?

**Comment by JKetelaar** [comment]
Agreed, but will it work instead?

**Comment by Fryslan** [comment]
Don't know about the MouseListener, but my issue is about clicking paints.

**Comment by JKetelaar** [comment]
Then I don't get your problem;
Where's the issue, with the mouse listener or clicking on paint parts?

**Comment by Fryslan** [comment]
The clicking the paint part

**Comment by JKetelaar** [comment]
What if you do:
```
BotDialog.getInstance().addMouseListener
```

**Comment by Fryslan** [comment]
That works for paints, thanks.
