### ISSUE TITLE
Paints/Debugs on mac

### ISSUE THREAD

**Issue by CapslockRSPS** [Parabot/Parabot#14]
So if i minimize parabot it shows the paint and debugs that show on screen but if i try to walk, open a tab it doesn't click but if i try to rotate the camera it works. I can only type if the "client" isn't selected it's like it makes 2 different clients.

**Comment by JKetelaar** [comment]
It's an issue in Java, will be resolved in JDK9.

**Comment by CapslockRSPS** [comment]
Thank you.
