### ISSUE TITLE
Elkoy still bans with Client version 2.6.3 with File>Randoms enabled

### ISSUE THREAD

**Issue by UFOSrReal** [Parabot/Parabot#160]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The Parabot version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

### Description
Mac, client 2.6.3

File>Random has 2 randoms(Onscreen and logout) randoms. But still all accounts are still getting banned within 5-10 minutes. Using local scripts and LordFisher(Another persons script)

**Comment by JKetelaar** [comment]
Have you tried deleting your cache (Elkoy), restarting the client and changing your mac address?

**Comment by UFOSrReal** [comment]
Replacing client, deleting cache, but not changing mac address. I thought about that, maybe they ban me cause of my recent accounts getting banned/pattern?..

**Comment by JKetelaar** [comment]
Could be, tried doing all above steps with a VPN?

**Comment by UFOSrReal** [comment]
I do not have a vpn, will look into the mac address

**Comment by UFOSrReal** [comment]
Still getting banned with changing mac address
