### ISSUE TITLE
PKH all npc ids equals -1

### ISSUE THREAD

**Issue by UFOSrReal** [Parabot/Parabot#163]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The Parabot version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

### Description
Mac, client version 2.6.3
Not much to say, but all npc ids, no matter what npc result in -1. Shows in debug and of course #interact and I'm sure all hooks. Thought maybe it was just debug saying wrong ID, tried attacking rock crabs(id:1265) and it only attacked when i put the value -1 in.

**Comment by CapslockRSPS** [comment]
It's caused by a wrong hook,

**Comment by CapslockRSPS** [comment]
Could you provide the json for the server please.

**Comment by UFOSrReal** [comment]
Sent

**Comment by CapslockRSPS** [comment]
Issue solved!
