### ISSUE TITLE
PkHonors #getPlane hook returns 0

### ISSUE THREAD

**Issue by UFOSrReal** [Parabot/Parabot#164]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The Parabot version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

### Description
Mac, client version 2.6.3
Using:
`Players.getMyPlayer().getLocation().getPlane()` 
is broken, tested on plane 3, and returns 0.

**Comment by CapslockRSPS** [comment]
#getPlane() seems to be for pathing, if you want to know the plane that you're at you simply do `Game.getPlane()`.
