### ISSUE TITLE
Cache clearing goes wrong

### ISSUE THREAD

**Issue by JKetelaar** [Parabot/Parabot#167]
System decides to clear all cache, no matter what. No clue why this is happening, on every restart.

**Comment by CapslockRSPS** [comment]
Does this happen on the nightly client or in the released version?

**Comment by JKetelaar** [comment]
Both versions

**Comment by CapslockRSPS** [comment]
Can it be because of [this](http://bdn.parabot.org/api/v2/bot/cache)?

**Comment by JKetelaar** [comment]
Is that being used anywhere?

**Comment by CapslockRSPS** [comment]
[Yes](https://github.com/Parabot/Parabot/blob/master/src/main/java/org/parabot/core/Core.java#L224).

**Comment by JKetelaar** [comment]
I lol'd, we should remove that and wait for BDN V3 for that

For now simply remove files older than 3 days.
