### ISSUE TITLE
GetSystemProp spam in console

### ISSUE THREAD

**Issue by UFOSrReal** [Parabot/Parabot#180]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The Parabot version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

### Description
Mac, client 2.6.4
Console gets spammed with:
`GetSystemProp user.home = /Users/name`
When you load a server, happens on all servers i believe. Spams when you load a server or even logged into a server. Makes it hard when debugging for scripts.

**Comment by JKetelaar** [comment]
Change this to Core.verbose, instead of system output

**Comment by CapslockRSPS** [comment]
Even with verbose it would spam the console for those debugging the client.

**Comment by JKetelaar** [comment]
True, but that wouldn't be our problem. As servers don't cache the value of the output they keep requesting it. 

Only thing we could do is request their value, but that might cause a suspicion, as some properties change over time and we're returning a cached value from before.

As for now just changing it to Core.verbose will be enough.
