### ISSUE TITLE
GameClient#doAction error in client when clicking

### ISSUE THREAD

**Issue by UFOSrReal** [Parabot/Parabot#181]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The Parabot version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

### Description
Mac, client 2.6.4
When you log in, and click, usually you get doAction error. You can't open any tabs, or logout. But you can walk. It's random, but spam clicking delete friends tab when first logging in helps(Fix from Lord)
Getting error(any server):
`java.lang.StackOverflowError
	at com.dreamscape.GameClient.doAction(GameClient.java)`

**Comment by CapslockRSPS** [comment]
This caused by the client and not Parabot.
