### ISSUE TITLE
Parabot Tr translation

### ISSUE THREAD

**Issue by Mertcantr** [Parabot/Parabot#212]
Parabot APK Turkish language support

**Comment by JKetelaar** [comment]
Thanks for the feedback, we will certainly implement this if someone's able to translate the strings for us.

**Comment by Mertcantr** [comment]
If APK is in Turkish into extras.pak, Turkish language becomes Turkish when it installs APK

**Comment by Mertcantr** [comment]
I added Turkish language into my yapim
