### ISSUE TITLE
Debugging actions doesn't have a default output

### ISSUE THREAD

**Issue by JKetelaar** [Parabot/Parabot#217]
When enabling Actions debug, none of the outputs are selected.
![image](https://user-images.githubusercontent.com/3681904/29686706-5332792e-891a-11e7-9992-cc3c4638cfd6.png)

Select `Output: 0` by default.

**Comment by CapslockRSPS** [comment]
Even if it isn't selected it will default to 0, `Output: 1` also doesn't work.

**Comment by JKetelaar** [comment]
It doesn't show it's selected.

**Comment by JKetelaar** [comment]
Is related to Parabot/Parabot-317-API-Minified

**Comment by AlexanderBielen** [comment]
PR https://github.com/Parabot/Parabot-317-API-Minified/pull/101 fixes this.
