### ISSUE TITLE
Can't register on forums, slack is invite-only

### ISSUE THREAD

**Issue by Shadowrs** [Parabot/Parabot#248]
@JKetelaar 

Hi Jeroen. Sorry about using Git to get in contact but I felt it was necessary. I've been looking over the forums and it looks like you're the last active staff member of Parabot, with Lord's last forum visit in May and the rest of the team not even in 2018. 

I understand most of you have probably moved on to other projects but I'm looking to explore ASM and RSPS bots, and I'd love to contribute. Recognising I can clone the open source repos (thank you!) in the mean time, I can only assume others now and then may visit Parabot and have the same issues I'm having. 

My old Parabot forum account is inaccessible, with no emails being received at my gmail or outlook addresses. I can't create a new forum account, and your other comms channel is Slack, which is invite only. 

I'm hoping you can resolve these issues by giving an hour or two to check out the forums and see if this is only an issue for me or others too. Beyond that, I'd really appreciate if I could make you a [Discord](https://discord.gg/MQjVtQ2) for Parabot. It's modern and open to all. While the community may be dying off, being an open source project is so important I don't want to see it totally fade. 

Thanks for your time.

**Comment by JKetelaar** [comment]
Thanks for getting into contact!

Could you send me your email address to jketelaar@parabot.org, so I can invite you to slack and solve these issues.
