### ISSUE TITLE
Custom action for randoms

### ISSUE THREAD

**Issue by JKetelaar** [Parabot/Parabot#270]
As some servers require custom actions on really specific moments, we would like those to be defined in the server provider, instead of the client.

So we could create a `RandomType.SERVER_CUSTOM`, whereas the method gets defined by the server provider.

This could allow us to create a random on login for example, with a callback on login (RuneWild).

**Comment by Shadowrs** [comment]
Closing as the UID spoof for RW has been implemented by using the login callback to perform spoofing at the right time.

`SERVER_CUSTOM` currently does not have any usages.
