### ISSUE TITLE
What is the outlook for parabot?

### ISSUE THREAD

**Issue by smeyerhot** [Parabot/Parabot#335]
### Short description
...

I heard from someone that this project is no longer being maintained. What is the outlook for this project? Is it worth trying to build this project and the minified api, internal api for botting with 2006Scape? I am getting a bunch of errors about certain api's not being available from maven repos...

### Steps to reproduce
...

### Extra information (Operating system, device, etc)
...

**Comment by JKetelaar** [comment]
API's are currently built on a private basis, so errors should definitely not occur and everything still works with the 317 servers.

Any specific errors you can share?

**Comment by smeyerhot** [comment]
The error I get in when I try to build the various projects with mvn. For example, the AIOWoodcutter example script fails with the following error. 
```
[ERROR] Failed to execute goal on project aio-woodcutter: Could not resolve dependencies for project src:aio-woodcutter:jar:1: Failed to collect dependencies at org.parabot:317-api-minified:jar:1.21.5: 

Failed to read artifact descriptor for org.parabot:317-api-minified:jar:1.21.5: Could not transfer artifact org.parabot:317-api-minified:pom:1.21.5 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [parabot-maven (http://maven.parabot.org/, default, releases+snapshots)] ->
```

It looks like there is no parabot repo at the following location:
```
https://repo.maven.apache.org/maven2/org/
```

**Comment by SandroCoutinho** [comment]
http://maven.parabot.org/ this is where the maven repo is

**Comment by smeyerhot** [comment]
Ok, I guess I just need to change those references in the AIOWoodcutter and API-minified, both of which seem to be trying to access the wrong maven repo.

**Comment by smeyerhot** [comment]
So, I got things working by compiling everything from source but still getting an error for the bot script. I will post on that repo

**Comment by JKetelaar** [comment]
You could also join our Slack:
https://join.slack.com/t/parabot/shared_invite/zt-804z2kfr-XyXc_nLUMBZX7RIH3f834Q
