### ISSUE TITLE
org.parabot maven dependencies are down

### ISSUE THREAD

**Issue by crispycritter99** [Parabot/Parabot#336]
### Short description
not sure what a local alternative would be
### Steps to reproduce
...

### Extra information (Operating system, device, etc)
...

**Comment by JKetelaar** [comment]
Good question, will check!

**Comment by crispycritter99** [comment]
Thanks for checking. It might also be beneficial to make a local alternative of the documentation, since https://bdn.parabot.org/docs/parabot is also inaccessible.

**Comment by crispycritter99** [comment]
I forked the project and put all the files in one so it should be usable without Maven.
