### ISSUE TITLE
NullPointer in RandomHandler

### ISSUE THREAD

**Issue by Kmodos** [Parabot/Parabot#57]
There is a possibility of a nullpointer exception going uncaught and crashing an active script at line 92 in RandomHandler.java

**Comment by JKetelaar** [comment]
Thanks, could you give the stacktrace?

**Comment by Kmodos** [comment]
Sure, as soon as I reproduce it

**Comment by demmonic** [comment]
A null got added to the collection, a stack trace isn't going to help anybody.. Add null checks, and stop exposing the random handler collections..
