### ISSUE TITLE
Search Refelction

### ISSUE THREAD

**Issue by ParabotLord** [Parabot/Parabot#62]
Add a search feature to refection and option to open all packages.

**Comment by JKetelaar** [comment]
Open all packages? Do you mean the classes by that?

**Comment by ParabotLord** [comment]
Expand all classes in the view rather than having to open them all the search.

**Comment by JKetelaar** [comment]
Pull request #63 contains the search feature.

**Comment by JKetelaar** [comment]
Pull request #63 now contains both of these features, which has been merged now!
