### ISSUE TITLE
New interface minor issues

### ISSUE THREAD

**Issue by JKetelaar** [Parabot/Parabot#68]
- These two lines do not match each others hight: 
![image](https://cloud.githubusercontent.com/assets/3681904/15304300/dc4742de-1bbc-11e6-96cf-a70b882fb47b.png)
- The login interface button seems off: 
![image](https://cloud.githubusercontent.com/assets/3681904/15304598/90433ce2-1bbe-11e6-8343-84431f486ca5.png)

**Comment by JKetelaar** [comment]
Could you try to resolve this @CapslockRSPS?

**Comment by CapslockRSPS** [comment]
Push Request #69 should fix it.

**Comment by JKetelaar** [comment]
Solved with PR #69, thanks a bunch @CapslockRSPS
